FROM python:3.12.5-alpine3.20

# create app directory
WORKDIR /app

# Install app dependencies
COPY src/requirements.txt ./

RUN pip install -r requirements.txt

# copy app source
COPY src /app

EXPOSE 8080
CMD ["python","server.py"]