FROM python:3.12.5-alpine3.20

# create app directory
WORKDIR /app

# Install app dependencies
COPY src/requirements.txt ./

RUN pip install -r requirements.txt

# copy app source
COPY src /app

EXPOSE 8080
# Define environment variable
ENV FLASK_APP=server.py

# Run the application with gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "server:app"]